name: Vegetation
main: net.weasel.Vegetation.Vegetation
version: 2.31_fixed
commands:
  mow:
    description: Mow the grass
    usage:
  grow:
    description: Grows the specified type of plant
    usage: "Usage: /grow [type]  (type = grass/flower/mushroom/cactus/cane)"
  growall:
    description: Grow everything (one cycle)
    usage: