name: Vegetation
main: net.weasel.Vegetation.Vegetation
version: 3.4
commands:
  mow:
    description: Mow the grass!
    usage:
  grow:
    description: Grows the specified type of plant
    usage: "Usage: /grow [type]  (type = flower/mushroom/cactus/sugar_cane/moss/scrub)"
  biome:
    description: Returns the biome type the player is currently standing on
    usage: "Usage: /biome"
  purge:
    description: Purges the data of grass and vine blocks
    usage: "Usage: /purge [type] (type = wild_grass, vines, tall_grass)"