name: Vegetation
main: net.weasel.Vegetation.Vegetation
version: 3.0
commands:
  mow:
    description: Mow the grass!
    usage:
  grow:
    description: Grows the specified type of plant
    usage: "Usage: /grow [type]  (type = flower/mushroom/cactus/sugar_cane/moss)"